# Generated by Django 4.2.1 on 2023-07-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30)),
                ('SURNAME', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=30)),
                ('REGISTRATION_DATE', models.DateTimeField()),
            ],
        ),
    ]
