# Generated by Django 4.2.1 on 2023-07-25 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='SURNAME',
        ),
        migrations.AddField(
            model_name='user',
            name='PASSWORD',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='REGISTRATION_DATE',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
