# Generated by Django 4.2.1 on 2023-06-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30)),
                ('SURNAME', models.CharField(max_length=30)),
                ('REGISTRATION_DATE', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LEVY', models.IntegerField()),
                ('MANUFACTURER', models.IntegerField()),
                ('MODEL', models.CharField(max_length=30)),
                ('PROD_YEAR', models.IntegerField()),
                ('CATEGORY', models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Universal', 'Universal'), ('Microbus', 'Microbus'), ('Goods wagon', 'Goods wagon'), ('Pickup', 'Pickup'), ('Cabriolet', 'Cabriolet'), ('Limousine', 'Limousine')], max_length=30)),
                ('LEATHER_INTERIOR', models.BinaryField()),
                ('FUEL_TYPE', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Hydrogen', 'Hydrogen')], max_length=30)),
                ('ENGINE_VOLUME', models.CharField(choices=[('0', '0'), ('0.1', '0.1'), ('0.2', '0.2'), ('0.2 Turbo', '0.2 Turbo'), ('0.3', '0.3'), ('0.3 Turbo', '0.3 Turbo'), ('0.4', '0.4'), ('0.4 Turbo', '0.4 Turbo'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.6 Turbo', '0.6 Turbo'), ('0.7', '0.7'), ('0.7 Turbo', '0.7 Turbo'), ('0.8', '0.8'), ('0.8 Turbo', '0.8 Turbo'), ('0.9', '0.9'), ('1', '1'), ('1.0 Turbo', '1.0 Turbo'), ('1.1', '1.1'), ('1.1 Turbo', '1.1 Turbo'), ('1.2', '1.2'), ('1.2 Turbo', '1.2 Turbo'), ('1.3', '1.3'), ('1.3 Turbo', '1.3 Turbo'), ('1.4', '1.4'), ('1.4 Turbo', '1.4 Turbo'), ('1.5', '1.5'), ('1.5 Turbo', '1.5 Turbo'), ('1.6', '1.6'), ('1.6 Turbo', '1.6 Turbo'), ('1.7', '1.7'), ('1.7 Turbo', '1.7 Turbo'), ('1.8', '1.8'), ('1.8 Turbo', '1.8 Turbo'), ('1.9', '1.9'), ('1.9 Turbo', '1.9 Turbo'), ('2', '2'), ('2.0 Turbo', '2.0 Turbo'), ('2.1', '2.1'), ('2.1 Turbo', '2.1 Turbo'), ('2.2', '2.2'), ('2.2 Turbo', '2.2 Turbo'), ('2.3', '2.3'), ('2.3 Turbo', '2.3 Turbo'), ('2.4', '2.4'), ('2.4 Turbo', '2.4 Turbo'), ('2.5', '2.5'), ('2.5 Turbo', '2.5 Turbo'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.7 Turbo', '2.7 Turbo'), ('2.8', '2.8'), ('2.8 Turbo', '2.8 Turbo'), ('2.9', '2.9'), ('2.9 Turbo', '2.9 Turbo'), ('3', '3'), ('3.0 Turbo', '3.0 Turbo'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.2 Turbo', '3.2 Turbo'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.5 Turbo', '3.5 Turbo'), ('3.6', '3.6'), ('3.6 Turbo', '3.6 Turbo'), ('3.7', '3.7'), ('3.7 Turbo', '3.7 Turbo'), ('3.8', '3.8'), ('3.9', '3.9'), ('4', '4'), ('4.0 Turbo', '4.0 Turbo'), ('4.2', '4.2'), ('4.2 Turbo', '4.2 Turbo'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.4 Turbo', '4.4 Turbo'), ('4.5', '4.5'), ('4.5 Turbo', '4.5 Turbo'), ('4.6', '4.6'), ('4.6 Turbo', '4.6 Turbo'), ('4.7', '4.7'), ('4.7 Turbo', '4.7 Turbo'), ('4.8', '4.8'), ('4.8 Turbo', '4.8 Turbo'), ('5', '5'), ('5.0 Turbo', '5.0 Turbo'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.4 Turbo', '5.4 Turbo'), ('5.5', '5.5'), ('5.5 Turbo', '5.5 Turbo'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.7 Turbo', '5.7 Turbo'), ('5.8', '5.8'), ('5.9', '5.9'), ('6', '6'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.3 Turbo', '6.3 Turbo'), ('6.4', '6.4'), ('6.7', '6.7'), ('6.8', '6.8'), ('7.3', '7.3'), ('20', '20')], max_length=30)),
                ('MILEAGE', models.IntegerField()),
                ('CYLINDERS', models.IntegerField()),
                ('GEAR_BOX_TYPE', models.CharField(choices=[('Automatic', 'Automatic'), ('Tiptronic', 'Tiptronic'), ('Variator', 'Variator'), ('Manual', 'Manual')], max_length=30)),
                ('DRIVE_WHEELS', models.CharField(choices=[('4x4', '4x4'), ('Front', 'Front'), ('Rear', 'Rear')], max_length=30)),
                ('DOORS', models.CharField(choices=[('04-may', '04-may'), ('02-mar', '02-mar'), ('>5', '>5')], max_length=30)),
                ('WHEEL', models.CharField(choices=[('Left wheel', 'Left wheel'), ('Right-hand drive', 'Right-hand drive')], max_length=30)),
                ('COLOR', models.CharField(choices=[('Silver', 'Silver'), ('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Green', 'Green'), ('Red', 'Red'), ('Sky blue', 'Sky blue'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Golden', 'Golden'), ('Beige', 'Beige'), ('Carnelian red', 'Carnelian red'), ('Purple', 'Purple'), ('Pink', 'Pink')], max_length=30)),
                ('AIRBUGS', models.IntegerField()),
                ('PRICE', models.FloatField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entering_data.person')),
            ],
        ),
    ]
