# Generated by Django 4.2.1 on 2023-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entering_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='AIRBUGS',
            field=models.IntegerField(verbose_name='airbugs'),
        ),
        migrations.AlterField(
            model_name='car',
            name='CATEGORY',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Universal', 'Universal'), ('Microbus', 'Microbus'), ('Goods wagon', 'Goods wagon'), ('Pickup', 'Pickup'), ('Cabriolet', 'Cabriolet'), ('Limousine', 'Limousine')], db_column='category', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='COLOR',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Green', 'Green'), ('Red', 'Red'), ('Sky blue', 'Sky blue'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Golden', 'Golden'), ('Beige', 'Beige'), ('Carnelian red', 'Carnelian red'), ('Purple', 'Purple'), ('Pink', 'Pink')], max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='CYLINDERS',
            field=models.IntegerField(verbose_name='cylinders'),
        ),
        migrations.AlterField(
            model_name='car',
            name='DOORS',
            field=models.CharField(choices=[('04-may', '04-may'), ('02-mar', '02-mar'), ('>5', '>5')], max_length=30, verbose_name='doors'),
        ),
        migrations.AlterField(
            model_name='car',
            name='DRIVE_WHEELS',
            field=models.CharField(choices=[('4x4', '4x4'), ('Front', 'Front'), ('Rear', 'Rear')], max_length=30, verbose_name='drive_wheels'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ENGINE_VOLUME',
            field=models.CharField(max_length=30, verbose_name='engine_volume'),
        ),
        migrations.AlterField(
            model_name='car',
            name='FUEL_TYPE',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Hydrogen', 'Hydrogen')], max_length=30, verbose_name='fuel_type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='GEAR_BOX_TYPE',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Tiptronic', 'Tiptronic'), ('Variator', 'Variator'), ('Manual', 'Manual')], max_length=30, verbose_name='gear_box_type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='car',
            name='LEATHER_INTERIOR',
            field=models.BinaryField(verbose_name='leather_interior'),
        ),
        migrations.AlterField(
            model_name='car',
            name='LEVY',
            field=models.IntegerField(verbose_name='levy'),
        ),
        migrations.AlterField(
            model_name='car',
            name='MANUFACTURER',
            field=models.CharField(max_length=15, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='MILEAGE',
            field=models.IntegerField(verbose_name='mileage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='MODEL',
            field=models.CharField(max_length=30, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='PRICE',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='PROD_YEAR',
            field=models.IntegerField(verbose_name='prod_year'),
        ),
        migrations.AlterField(
            model_name='car',
            name='WHEEL',
            field=models.CharField(choices=[('Left wheel', 'Left wheel'), ('Right-hand drive', 'Right-hand drive')], max_length=30, verbose_name='wheel'),
        ),
    ]
